Feat: search by hashtag
prj154654168/Sooum-BE pull request #112
Opened 2024-10-04 07:00 UTC by KoungQ

2024-10-04 15:20 UTC, LeeKing2017 requested changes

2024-10-04 15:20 UTC, LeeKing2017 commented on src/main/java/com/sooum/core/domain/tag/entity/Tag.java
> +    private Boolean isActive;
null값이 들어갈 일이 없으니 wrapper type이 아닌 primitive 타입을 사용하는 편이 더 좋을 것 같습니다.

2024-10-05 15:35 UTC, jang-199 submitted a review, later dismissed

2024-10-06 14:27 UTC, jiixon approved these changes

2024-10-06 14:28 UTC, LeeKing2017 approved these changes

2024-10-06 14:28 UTC, merged