Feat: favorite tags retrieval api
prj154654168/Sooum-BE pull request #145
Opened 2024-10-13 16:02 UTC by jiixon

즐겨찾기 태그조회 API 입니다.
각 태그별로 미리보기 카드 5개가 존재합니다. 각 태그의 피드를 조회하도록 다음링크를 주고, 미리보기 카드 내에서도 해당 카드 상세보기로 링크를 함께 반환합니다.

1.즐겨찾기 조회시 20개를 페이징처리해서 반환하는데, 즐겨찾기를 등록한 순으로 조회하도록 했습니다.
2.미리보기 카드 5개 조회하는 쿼리 - ispublic, isdeleted, blockmember의 feedcard 제외를 고려하였습니다.
     - feedcard를 가져와야해서 join을 썼습니다.

위 부분에서 제가 놓친 것이 있거나 혹은 더 좋은 로직이 있다면 피드백 주시면 감사하겠습니다!

2024-10-13 16:24 UTC, LeeKing2017 requested changes

2024-10-13 16:24 UTC, LeeKing2017 commented on src/main/java/com/sooum/core/domain/tag/service/FavoriteTagService.java
> +        return TagDto.FavoriteTag.builder()
만약 찾은 글이 아무것도 없다면 빈 리스트가 반환되고
`Tag tag = relatedFeedTags.get(0).getTag();`

부분에서 NPE가 발생할 거 같은데 혹시 테스트 됐을까요?

2024-10-13 17:43 UTC, jiixon commented on src/main/java/com/sooum/core/domain/tag/service/FavoriteTagService.java
> +        return TagDto.FavoriteTag.builder()
태그의 카드 없으면 빈리스트로 반환되고, 즐겨찾기 pk로 tag 객체 가져오도록 수정했습니당!

2024-10-13 17:56 UTC, LeeKing2017 commented on src/main/java/com/sooum/core/domain/tag/service/FavoriteTagService.java
> +        return TagDto.FavoriteTag.builder()
태그가 최대 20개까지 조회할 수 있는데 tag를 하나씩 가져오면 20번의 조회 쿼리가 나갈 것 같습니다

2024-10-13 18:17 UTC, jiixon commented on src/main/java/com/sooum/core/domain/tag/service/FavoriteTagService.java
> +        return TagDto.FavoriteTag.builder()
list로 받아서 가져온후 맵핑하도록 바꿨습니당~

2024-10-14 03:11 UTC, jang-199 approved these changes

2024-10-14 08:45 UTC, jang-199 approved these changes

2024-10-14 13:43 UTC, LeeKing2017 approved these changes
수고하셨습니다~

2024-10-14 13:43 UTC, merged