feat: card detail api
prj154654168/Sooum-BE pull request #83
Opened 2024-09-26 09:05 UTC by jiixon

카드 상세조회 AP를 구현하였습니다.
member, detailCard, tags를 반환합니다.
또한 각 태그별로 nextLink도 함께 반환합니다.

2024-09-26 10:06 UTC, LeeKing2017 commented
저희는 카드 상세보기가 feedcard일수도 있고 comment카드일수도 있는데 이 부분 반영안된 것 같습니다. Api를 따로 분리하실 생각이실까요??

2024-09-26 16:41 UTC, jiixon commented
> 저희는 카드 상세보기가 feedcard일수도 있고 comment카드일수도 있는데 이 부분 반영안된 것 같습니다. Api를 따로 분리하실 생각이실까요??

따로 분리할 예정입니다! 나머지 수정해야하는 상황 반영했습니다~!

2024-09-26 16:48 UTC, LeeKing2017 commented on src/main/java/com/sooum/core/domain/card/controller/FeedCardController.java
> +    @GetMapping("/detail/{cardId}")
cards/{cardId}/detail이 더 restful한 것 같습니다.

2024-09-26 16:48 UTC, LeeKing2017 commented on src/main/java/com/sooum/core/domain/card/dto/DetailCardDto.java
> +    public static class DetailFeedCard extends RepresentationModel<DetailFeedCard> {
유사한 점이 많은 cardDto를 상속받아 사용하는 편이 더 유지보수면에서 좋을 것 같습니다

2024-09-26 16:50 UTC, jiixon commented on src/main/java/com/sooum/core/domain/card/controller/FeedCardController.java
> +    @GetMapping("/detail/{cardId}")
엇 넹~ 수정하겠습니당

2024-09-26 16:50 UTC, KoungQ submitted a review, later dismissed

2024-09-27 00:59 UTC, jang-199 commented
> 저희는 카드 상세보기가 feedcard일수도 있고 comment카드일수도 있는데 이 부분 반영안된 것 같습니다. Api를 따로 분리하실 생각이실까요??

feedCard pk, commentCardPk 둘 다 tsid로 생성하고 있어 두 카드의 pk가 동일하게 생성될 경우는 고려하지 않고 구현해도 상관없을 것 같습니다. 하여 parameter로 cardId만 받아 feedCardService 와 commentCardService에서 함께 검색하여 검색된 카드를 사용하여 핸들링하는 방식으로 진행하면 좋을 것 같습니다.

_추후 보다 정확한 Test 과정을 거친 후 pk가 충돌되는 케이스가 발견되면 pk에 prefix를 추가하여 테이블을 구분하는 방식으로 refactoring하면 될 것 같습니다. 이 점 참고 바라며 상기 내용 고려하여 commentCard, feedCard 상세조회 api는 구분없이 하나의 공통 api에서 처리하는 방식으로 구현하는 것을 제안합니다._

2024-09-27 01:06 UTC, jang-199 requested changes
다 잘 해주셨지만 코멘트 남겨놓은 부분만 추가로 확인하시고 수정 후 다시 논의 해봐요 :)

2024-09-28 21:04 UTC, jang-199 approved these changes

2024-09-28 22:03 UTC, LeeKing2017 approved these changes
수고하셨습니다~

2024-09-28 22:03 UTC, merged